name: Run Jupyter Notebook and Notify

on:
    push:
        paths:
            - SalesForecastPipeline.ipynb
   workflow_dispatch:

jobs:
    execute-notebook:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/checkout@v4
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: |
                 python -m pip install --upgrade pip
                 pip install nbconvert notebook jupyter

            - name: Execute Notebook
               run: |
                  jupyter nbconvert --to notebook --execute SalesForcastPipeline.ipynb --output executed.ipynb || echo "Notebook eecution failed" > error.log

            - name: Check for Errors
               id: check_error
               run: |
               if [ -s error.log]; then
                  echo "error=true" >> $GITHUB_OUTPUT

               else
                  echo "error=false" >> $GITHUB_OUTPUT

            - name: Send Email with Sendmail
               if: steps.check_error.outputs.error == "true"

               run: |
               echo -e "Subject: Jupyter Notebook Failed\n\n The notebook SalesForecastPipeline.ipynb failed during execution." | send your_email@example.com
